### ISSUE TITLE
loading akrOS takes a long time. we need a loading screen

### ISSUE THREAD

**Issue by abenkovskii** [akrasuski1/akrOS#27]

**Comment by akrasuski1** [comment]
Will printing "Loaded window library." etc. after each `run` in `akros_system` be fine?

**Comment by abenkovskii** [comment]
Fine. A progress bar will be nice though.

**Comment by akrasuski1** [comment]
ok. I'll do a quick fix (as above) and then mark the issue as low priority for implementing the nice progress bar.

EDIT: Done quick fix ("command line" loading messages).

**Comment by akrasuski1** [comment]
Now, I think we don't really need the progress bar. There are two cases: first, we use compiled program (.ksm) - then, the loading speed is increased dramatically, so user is not frustrated waiting. Otherwise, we use source (.ks) files - then, the whole KSP is frozen for compilation, and the terminal barely updates, making the progress bar useless.

Closing as wontfix.
